[["example_schema.events"]]
filter = "delete"

[["public.users"]]
filter = "file replace"
columns = ["name"]
source = "testdata/newnames.txt"

[["public.users"]]
filter = "string replace"
columns = ["password"]
# give all users the same password
replacements = ["$2a$06$.wHg4l7yz1ijSfMwa7fNruq3ASx1plpkC.XcI1wXdghCb4ZJQsrtC"]

[["public.users"]]
filter = "file replace"
columns = ["notes"]
# cycle through 3 example notes
source = "testdata/newnotes.txt"
