title = "example settings file for gopg-anonymiser"

[tables]

[tables.messages]
tablename = "public.messages"

[[tables.messages.filters]]
column = "all"
filter = "delete"
# source = ""

[tables.users]
tablename = "public.users"

[[tables.users.filters]]
column = "name"
filter = "file_replace"
source = "/tmp/newnames.txt"

[[tables.users.filters]]
column = "password"
filter = "string_replace"
source = "this is a password"



