/*
Test postgresql table and contents file, for dumping via pg_dump
*/


-- a users table
DROP TABLE IF EXISTS public.users;

CREATE TABLE public.users (
    id INT GENERATED BY DEFAULT AS IDENTITY
    ,name TEXT NOT NULL
    ,age INT NOT NULL
    ,password TEXT NOT NULL -- use crypt(in_password, gen_salt('bf'))
    ,notes TEXT
);


-- a new schema
DROP SCHEMA IF EXISTS example_schema CASCADE;

CREATE schema IF NOT EXISTS example_schema;

-- a table in the new schema
CREATE TABLE example_schema.events (
    id INT GENERATED BY DEFAULT AS IDENTITY
    ,flags TEXT[]
    ,data jsonb
);

/*
as postgres
create schema extensions;
create extension pgcrypto with schema extensions;
grant usage on schema extensions to <user>
*/

SET search_path = public, example_schema, extensions;

INSERT INTO users (name, age, password) VALUES
('ariadne', 22, crypt('test1', gen_salt('bf')))
,('james', 17, crypt('test2', gen_salt('bf')))
,('lucius', 77, crypt('test3', gen_salt('bf')))
;

INSERT INTO users (name, age, password, notes) VALUES
('biggles', 8, crypt('test4', gen_salt('bf')), 'a ''note''')
,('asterix', 7, crypt('test5', gen_salt('bf')), 'a "note", with commas, etc.')
,('wormtail', 99, crypt('test6', gen_salt('bf')), 'a note with a tab here:"	"')
;

INSERT INTO events (flags, data) VALUES
(array['flag1', 'flag2'], '{"a": "b"}')
,(array['flag1,a', 'flag2,b'], '{"a": "c,b", "b": [1, 0]}')
,(array['flag3'], '{"c": null}')
,(array['flag3	tab'], '{"d": "x  y"}')
;
