--
-- PostgreSQL database dump
--

-- Dumped from database version 12.10 (Debian 12.10-1.pgdg100+1)
-- Dumped by pg_dump version 12.10 (Debian 12.10-1.pgdg100+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: example_schema; Type: SCHEMA; Schema: -; Owner: dbuser
--

CREATE SCHEMA example_schema;


ALTER SCHEMA example_schema OWNER TO dbuser;

--
-- Name: extensions; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA extensions;


ALTER SCHEMA extensions OWNER TO postgres;

--
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;


--
-- Name: EXTENSION pgcrypto; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: events; Type: TABLE; Schema: example_schema; Owner: dbuser
--

CREATE TABLE example_schema.events (
    id integer NOT NULL,
    flags text[],
    data jsonb
);


ALTER TABLE example_schema.events OWNER TO dbuser;

--
-- Name: events_id_seq; Type: SEQUENCE; Schema: example_schema; Owner: dbuser
--

ALTER TABLE example_schema.events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME example_schema.events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: dbuser
--

CREATE TABLE public.users (
    id integer NOT NULL,
    name text NOT NULL,
    age integer NOT NULL,
    password text NOT NULL,
    notes text
);


ALTER TABLE public.users OWNER TO dbuser;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: dbuser
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: events; Type: TABLE DATA; Schema: example_schema; Owner: dbuser
--

COPY example_schema.events (id, flags, data) FROM stdin;
1	{flag1,flag2}	{"a": "b"}
2	{"flag1,a","flag2,b"}	{"a": "c,b", "b": [1, 0]}
3	{flag3}	{"c": null}
4	{"flag3\ttab"}	{"d": "x  y"}
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: dbuser
--

COPY public.users (id, name, age, password, notes) FROM stdin;
1	ariadne	22	$2a$06$6NX0WOwJ7i57BXi7E8bR.OS3C1/B/C3O3s9O7XCdxQtYKi6HY/K8G	\N
2	james	17	$2a$06$jipeOgnD0Ibpa5hyTgtnwuwrYFVlwEitl8plrC7vJ4W8uN76i0WUK	\N
3	lucius	77	$2a$06$zT9WAgHzuKQkhq6ghnA9VuhK11t3pvx7AEHz6ed5NhpUwaJocAfe2	\N
4	biggles	8	$2a$06$ICaf31zcP4VyxBHqnmd3VefOhQUurllaAZqQk2Cq8yVXHmNOj9RJe	a 'note'
5	asterix	7	$2a$06$fokqEHm2.Pxsa1wDDW9kg.QxTyh4X90TX05oI7tr1b1OtuX.SFbLm	a "note", with commas, etc.
6	wormtail	99	$2a$06$.wHg4l7yz1ijSfMwa7fNruq3ASx1plpkC.XcI1wXdghCb4ZJQsrtC	a note with a tab here:"\t"
\.


--
-- Name: events_id_seq; Type: SEQUENCE SET; Schema: example_schema; Owner: dbuser
--

SELECT pg_catalog.setval('example_schema.events_id_seq', 4, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dbuser
--

SELECT pg_catalog.setval('public.users_id_seq', 6, true);


--
-- Name: SCHEMA extensions; Type: ACL; Schema: -; Owner: postgres
--

GRANT USAGE ON SCHEMA extensions TO dbuser;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

GRANT ALL ON SCHEMA public TO dbuser;


--
-- PostgreSQL database dump complete
--

